name: "build"
on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v3
      with:
        name: allvm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
