name: "build"
on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v16
    - uses: cachix/cachix-action@v10
      with:
        name: allvm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
